### PR TITLE
Add swedish language (with tests)

### PR DESCRIPTION
**Pull request by mhaamann**
Based on:
https://github.com/adamwdraper/Numeral-js/pull/299/files

With help from:
http://www.localeplanet.com/icu/sv-SE/index.html

---
This change is [Reviewable](https://reviewable.io/reviews/adamwdraper/numeral-js/506)

### CODE REVIEW

**Comment by mhaamann** [comment]
Hi @adamwdraper

After running `grunt dist` the following files were modified. I chose not to commit those changes since it does not relate to my PR. Just a heads up.
```
modified:   min/locales/en-au.min.js
modified:   min/locales/en-gb.min.js
modified:   min/locales/en-za.min.js
modified:   min/locales/nl-be.min.js
modified:   min/locales/nl-nl.min.js
```

**Comment by mhaamann** [comment]
Author not responding. Closing

**Comment by OvidiuBan** [comment]
@adamwdraper Will this be implemented?

**Comment by mhaamann** [comment]
@OvidiuBan: I can recommend http://numbrojs.com/, that is what we switched to.

**Pull request closed without merging**
