### PR TITLE
Adding an option so numeral wouldn't scale percentage up/down by 100 automatically

### PR DESCRIPTION
**Pull request by MrCsabaToth**

### CODE REVIEW

**Comment by MrCsabaToth** [comment]
Fixes #329

**Comment by MrCsabaToth** [comment]
Let me know what should I change in term of styling, logic or tests. I'd like this to be in the next release of possible.

**Comment by adamwdraper** [comment]
Thanks

**Comment by MIHDashboard** [comment]
+1

**Pull request merged**
